[package]
name = "gitignore-copy"
version = "0.1.3"
authors = ["Eric Vincent <eric@efvincent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
gitignore = "1.0.6"